// JAVASCRIPT KODLARINI WEBDE ÇALIŞTIRAN EKLENTI ÇIKARILIP AYRI BIR UZANTI OLARAK PROGRAMLAYA KATILDIĞI İÇİN KODLARI TERMINALDENDE CALISTIRABILIYORUZ
console.log("Emre Üçbudak")
// BU UZANTININ ADI JQUERY